# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Android Stuff
author: David Medenjak
email: davidmedenjak@gmail.com
description: "A blog about Android."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.davidmedenjak.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  bleeding182

exclude:
  - CNAME
  - README.md
  - Guardfile
  - Gemfile
  - Gemfile.lock
  - CLAUDE.md
  - node_modules
  - package.json
  - package-lock.json
  - rollup.config.js
  - src
  - vendor

# Build settings
markdown: kramdown
future: true

sass:
    style: compressed

# Performance optimizations
incremental: false

# Fix file watching on WSL
force_polling: true

liquid:
  error_mode: warn
  strict_filters: false
  strict_variables: false

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      author: David Medenjak

paginate: 8

repository: username/repo-name

plugins:
  - jekyll-sitemap
